### ISSUE TITLE
Connecting Ignition with MSSQL

### ISSUE THREAD

**Issue by JoeriIndenKleef** [thirdgen88/ignition-examples#3]
Hi,

I love this idea!
But don't get a connection between Ignition and MSSQL.
I got the following message:
![image](https://user-images.githubusercontent.com/36849070/82243562-23744300-9940-11ea-9dff-02941063c0f8.png)
I think this has to do with the SQL server browser or the TCP Ip enable.
I couldn't find the solution on Google.

**Comment by thirdgen88** [comment]
@JoeriIndenKleef, double check your connection URL; specifically, make sure it does **NOT** include `\MSSQLSERVER`, as this uses SQL Server Browser to resolve.  I just did a fresh _pull_ and _up_ and with the connection settings in the README, it worked for me.  

Other thing to check is that you’ve properly created your secrets files.  Please provide some additional insights on your configuration if you’re still having trouble, I’m glad to help!

**Comment by thirdgen88** [comment]
On further inspection, it appears you’re reaching the SQL container, you’re just getting login failed.  Did you set the same password in Ignition for the connection as was in your `secrets/MSSQL_PASSWORD` file?

**Comment by JoeriIndenKleef** [comment]
@thirdgen88, 
I did use you're read me but my files are a little bit different, see zip:
[Ignition.zip](https://github.com/thirdgen88/ignition-examples/files/4654904/Ignition.zip)
I tried to connect to the DB without the \MSSQLSERVER. 
Also, I think the secrets are set up correctly.

**Comment by thirdgen88** [comment]
@JoeriIndenKleef, if you were to do a `docker-compose logs -f db` on first launch, you'd likely see this error:
```
2020-05-20 11:57:03.82 spid28s     ERROR: Unable to set system administrator password: Password validation failed. The password does not meet SQL Server password policy requirements because it is not complex enough. The password must be at least 8 characters long and contain characters from three of the following four sets: Uppercase letters, Lowercase letters, Base 10 digits, and Symbols..
2020-05-20 11:57:03.83 spid28s     An error occurred during server setup. See previous errors for more information.
2020-05-20 11:57:03.83 spid28s     SQL Trace was stopped due to server shutdown. Trace ID = '1'. This is an informational message only; no user action is required.
```
SQL Server is more strict on password requirements by default (honestly, I'm not sure how to tell it not to be, but perhaps there is a way), so if you have a simple password (like the `password` in your example secrets file), it will fail to absorb it and exit.  Unfortunately, subsequent starts of the container (against the preserved volume) don't exit in the same way, but rather hang out in limbo with an unknown set of credentials (making it hard to debug).

I will add a note to the README about this, as I could see this being a common point of confusion.  Let me know if you are able to get it going after wiping your volume, correcting your password secrets for `MSSQL_PASSWORD` and `SA_PASSWORD` and restarting the DB.  Easiest way is with a `docker-compose down -v`, but make sure that you don't have anything you care about in the Ignition gateway either, as it will remove all volumes in the stack.

**Comment by thirdgen88** [comment]
@JoeriIndenKleef, any luck with the guidance above?

**Comment by JoeriIndenKleef** [comment]
@thirdgen88  Yes, I did. 
I changed the password and it works perfectly. 
Thank you!

**Comment by thirdgen88** [comment]
Closing this one out to clean things up.  👍
